# Generated by Django 4.2.7 on 2023-12-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=20)),
                ('health', models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='chattext',
            name='answer_player',
            field=models.TextField(default='нечего не выдавай'),
        ),
    ]
